name: Step 2 # Explaining legacy code

on:
  push:
    branches:
      - "modernize-legacy-code"
    paths:
      - "docs/*"

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_2_FILE: ".github/steps/3-create-test-plan.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.6.0

  check_step_work:
    name: Check step work
    runs-on: ubuntu-latest
    needs: [find_exercise]
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.6.0

      - name: Update comment - checking work
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/checking-work.md \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # START: Check practical exercise

      - name: Check for an explanation of data.cob
        id: check-explanation-data-cob
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: docs/README.md
          keyphrase: 'data.cob'
          minimum-occurrences: 1
          case-sensitive: false

      - name: Check for an explanation of main.cob
        id: check-explanation-main-cob
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: docs/README.md
          keyphrase: 'main.cob'
          minimum-occurrences: 1
          case-sensitive: false

      - name: Check for an explanation of operations.cob
        id: check-explanation-operations-cob
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: docs/README.md
          keyphrase: 'operations.cob'
          minimum-occurrences: 1
          case-sensitive: false

      - name: Check for a mermaid diagram
        id: check-mermaid-diagram
        continue-on-error: true
        uses: skills/action-keyphrase-checker@v1
        with:
          text-file: docs/README.md
          keyphrase: 'mermaid'
          minimum-occurrences: 1
          case-sensitive: false

      - name: Build message - step results
        id: build-message-step-results
        uses: skills/action-text-variables@v2
        with:
          template-file: exercise-toolkit/markdown-templates/step-feedback/step-results-table.md
          template-vars: |
            step_number: 2
            passed: ${{ !contains(steps.*.outcome, 'failure') }}
            results_table:
              - description: "Check README.md for an explanation of data.cob"
                passed: ${{ steps.check-explanation-data-cob.outcome == 'success' }}
              - description: "Check README.md for an explanation of main.cob"
                passed: ${{ steps.check-explanation-main-cob.outcome == 'success' }}
              - description: "Check README.md for an explanation of operations.cob"
                passed: ${{ steps.check-explanation-operations-cob.outcome == 'success' }}
              - description: "Check README.md for a mermaid diagram"
                passed: ${{ steps.check-mermaid-diagram.outcome == 'success' }}

      # END: Check practical exercise

      - name: Create comment - step results
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "$COMMENT_BODY" \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: ${{ steps.build-message-step-results.outputs.updated-text }}

      - name: Fail job if not all checks passed
        if: contains(steps.*.outcome, 'failure')
        run: exit 1


  post_next_step_content:
    name: Post next step content
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.6.0

      - name: Build message - step finished
        id: build-message-step-finish
        uses: skills/action-text-variables@v2
        with:
          template-file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
          template-vars: |
            next_step_number: 3

      - name: Create comment - step finished
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "$ISSUE_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_BODY: ${{ steps.build-message-step-finish.outputs.updated-text }}

      - name: Create comment - add step content
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file "$STEP_2_FILE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create comment - watching for progress
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Disable current workflow and enable next one
        run: |
          gh workflow disable "${{github.workflow}}"
          gh workflow enable "Step 3"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
